<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="spring-transaction"><a href="#spring-transaction">Spring Transaction</a></h2>
    <p><code class="inline-code-block">@Transactional</code></p>
    <blockquote>
      <p>스프링에서 제공하는 어노테이션으로, 메소드나 클래스에 적용할 수 있습니다.</p>
      <p>이 어노테이션은 프록시 객체를 생성하여 트랜잭션을 관리합니다. (PlatformTransactionManager)</p>
      <p>import org.springframework.transaction.annotation.Transactional; 을 사용해야 합니다.</p>
      <p>javax.transaction.Transactional 은 옵션 설정이 불가능합니다.</p>
    </blockquote>
    <h3 id=""><a href="#">세부설정</a></h3>
    <h4 id="isolation"><a href="#isolation">Isolation (격리수준)</a></h4>
    <blockquote>
      <p>트랜잭션 격리수준은 트랜잭션에서 일관성 없는 데이터를 허용하도록 하는 수준을 말합니다.</p>
    </blockquote>
    <ul>
      <li>
        <code class="inline-code-block">DEFAULT</code>
         : DB의 기본 격리수준을 따릅니다.
      </li>
      <li>
        <code class="inline-code-block">READ_UNCOMMITTED</code>
        : 커밋되지 않은 데이터에 대한 읽기를 허용합니다.
        <ul>
          <li>Dirty Read 발생 (커밋되지 않은 데이터를 읽을 수 있음)</li>
        </ul>
      </li>
      <li>
        <code class="inline-code-block">READ_COMMITTED</code>
        : 커밋된 데이터만 읽기를 허용합니다.
        <ul>
          <li>Dirty Read 방지</li>
        </ul>
      </li>
      <li>
        <code class="inline-code-block">REPEATABLE_READ</code>
        : 트랜잭션 내에서 SELECT 시 같은 데이터를 읽어도 항상 같은 데이터가 조회됩니다.
        <ul>
          <li>Non-Repeatable Read 발생 (같은 데이터를 읽었는데 다른 데이터가 조회됨)</li>
        </ul>
      </li>
      <li>
        <code class="inline-code-block">SERIALIZABLE</code>
        : 트랜잭션 내에서 SELECT 시 같은 데이터를 읽어도 항상 같은 데이터가 조회되며, 트랜잭션이 완료될 때까지 다른
        트랜잭션에서는 해당 데이터에 대한 변경이 불가능합니다.
        <ul>
          <li>Phantom Read 발생 (같은 데이터를 읽었는데 다른 데이터가 조회됨)</li>
        </ul>
      </li>
    </ul>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-java">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token annotation punctuation">@Transactional</span><span class="token punctuation">(</span>isolation <span class="token operator">=</span> <span class="token class-name">Isolation</span><span class="token punctuation">.</span><span class="token constant">DEFAULT</span><span class="token punctuation">)</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h4 id="propagation"><a href="#propagation">Propagation (전파수준)</a></h4>
    <blockquote>
      <p>트랜잭션 동작 도중 다른 트랜잭션을 호출할 경우, 어떻게 동작할지를 결정하는 수준을 말합니다.</p>
    </blockquote>
    <ul>
      <li>
        <code class="inline-code-block">REQUIRED</code>
         : 부모 트랜잭션이 존재하면 해당 트랜잭션을 사용하고, 없으면 새로운 트랜잭션을 생성합니다. (기본값)
      </li>
      <li>
        <code class="inline-code-block">SUPPORTS</code>
         : 부모 트랜잭션이 존재하면 해당 트랜잭션을 사용하고, 없으면 트랜잭션 없이 진행합니다.
      </li>
      <li>
        <code class="inline-code-block">REQUIRES_NEW</code>
         : 부모 트랜잭션이 존재하더라도 새로운 트랜잭션을 생성합니다.
      </li>
      <li>
        <code class="inline-code-block">NESTED</code>
        : 부모 트랜잭션이 존재하면 중첩된 트랜잭션을 생성합니다. (부모 트랜잭션 안에 있는 트랜잭션)
        <ul>
          <li>예시) 일기 작성 관련해서 로그를 DB에 저장하는 상황</li>
          <li>
            <ol>
              <li>로그 저장(중첩된 트랜잭션)이 실패한다해도 일기 작성(부모 트랜잭션)은 성공해야 함</li>
            </ol>
          </li>
          <li>
            <ol start="2">
              <li>일기 작성(부모 트랜잭션)이 실패한다면 로그 저장(중첩된 트랜잭션)까지 롤백되어야 함</li>
            </ol>
          </li>
        </ul>
      </li>
    </ul>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-java">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token annotation punctuation">@Transactional</span><span class="token punctuation">(</span>propagation <span class="token operator">=</span> <span class="token class-name">Propagation</span><span class="token punctuation">.</span><span class="token constant">REQUIRED</span><span class="token punctuation">)</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h4 id="readonly"><a href="#readonly">ReadOnly 속성</a></h4>
    <blockquote>
      <p>트랜잭션 동작 도중 데이터를 변경하지 않는다면, 해당 트랜잭션을 읽기 전용으로 설정할 수 있습니다.</p>
    </blockquote>
    <ul>
      <li>
        <code class="inline-code-block">readOnly = true</code>
         : 트랜잭션 동작 도중 데이터를 변경하지 않습니다.
      </li>
      <li>
        <code class="inline-code-block">readOnly = false</code>
         : 트랜잭션 동작 도중 데이터를 변경합니다. (기본값)
      </li>
    </ul>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-java">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token annotation punctuation">@Transactional</span><span class="token punctuation">(</span>readOnly <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">)</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h4 id=""><a href="#">트랜잭션 롤백 예외</a></h4>
    <blockquote>
      <p>트랜잭션 동작 도중 특정 예외가 발생하면 트랜잭션을 롤백할 수 있습니다.</p>
      <p>Defalut : RuntimeException , Error</p>
    </blockquote>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-java">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token annotation punctuation">@Transactional</span><span class="token punctuation">(</span>rollbackFor <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token class-name">Exception</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// Exception 예외가 발생하면 트랜잭션을 롤백합니다.</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token annotation punctuation">@Transactional</span><span class="token punctuation">(</span>noRollbackFor <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token class-name">Exception</span><span class="token punctuation">.</span><span class="token keyword">class</span><span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// Exception 예외가 발생해도 트랜잭션을 롤백하지 않습니다.</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h4 id="timeout"><a href="#timeout">timeout 속성</a></h4>
    <blockquote>
      <p>트랜잭션 동작 도중 특정 시간이 초과되면 트랜잭션을 롤백할 수 있습니다.</p>
      <p>Default : -1 (무제한)</p>
    </blockquote>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-java">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token annotation punctuation">@Transactional</span><span class="token punctuation">(</span>timeout <span class="token operator">=</span> <span class="token number">10</span><span class="token punctuation">)</span> <span class="token comment">// 10초가 초과되면 트랜잭션을 롤백합니다.</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
  </article>
</Post>
