<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>
      <code class="inline-code-block">REST</code>
       : REpresentational State Transfer
    </p>
    <p>
      REST는 하나의 아키텍처 스타일로, 웹 서비스를 자원(Resource) 중심으로 설계하고, HTTP 메소드를 통해 자원을 처리하는
      방식입니다. 이를 <code class="inline-code-block">Resource Oriented Architecture</code>
      라고도 합니다. API 설계의 중심에 자원이 있으며, 자원의 상태와 행위르롤 명시적이고 직관적으로 분리합니다.
    </p>
    <p>
      💡 <strong>REST 6가지 원칙</strong>
    </p>
    <ol>
      <li>
        <code class="inline-code-block">Uniform Interface</code>
         : 표준화된 인터페이스를 사용하여 상호작용을 단순화하고 일관성을 유지합니다.
      </li>
      <li>
        <code class="inline-code-block">Stateless</code>
         : 각 요청이 독립적이고, 서버가 클라이언트의 상태 정보를 저장하지 않습니다.
      </li>
      <li>
        <code class="inline-code-block">Caching</code>
         : 응답 결과에 캐싱 정보를 포함하여 네트워크 부하를 줄이고 성능을 향상시킵니다.
      </li>
      <li>
        <code class="inline-code-block">Client-Server</code>
         : 클라이언트와 서버가 역할을 분리하여 서로에 영향을 미치지 않습니다.
      </li>
      <li>
        <code class="inline-code-block">Hierarchical System</code>
         : 시스템을 계층적으로 구성하여 보안, 로드 밸런싱, 캐싱 등을 적용할 수 있습니다.
      </li>
      <li>
        <code class="inline-code-block">Code on demand</code>
         : 필요한 경우에만 클라이언트에 코드를 전송하여 기능을 확장할 수 있습니다.
      </li>
    </ol>
    <h2 id="restful-api"><a href="#restful-api">RESTful하게 API를 디자인 한다는 것은 무엇을 의미할까?</a></h2>
    <ol>
      <li>
        리소스와 행위를 명시적이고 직관적으로 분리합니다.
        <ol>
          <li>
            리소스는 <code class="inline-code-block">URI</code>
            로 표현되며, 리소스가 가리키는 것은
            <code class="inline-code-block">명사</code>
            로 표현합니다.
          </li>
          <li>
            행위는 <code class="inline-code-block">HTTP Method</code>
            로 표현하며,
            <code class="inline-code-block">GET</code>
            ,
            <code class="inline-code-block">POST</code>
            ,
            <code class="inline-code-block">PUT</code>
            ,
            <code class="inline-code-block">PATCH</code>
            ,
            <code class="inline-code-block">DELETE</code>
            를 각각의 목적에 맞게 사용합니다.
          </li>
        </ol>
      </li>
      <li>
        Message는 Header와 Body를 명확하게 분리해서 사용합니다.
        <ol>
          <li>Entity에 대한 내용은 body에 담습니다.</li>
          <li>
            애플리케이션 서버가 행동할 판단의 근거가 되는 컨트롤 정보인 API 버전 정보, 응답받고자 하는 MIME 타입 등은
            header에 담습니다.
          </li>
          <li>
            header와 body는 http header와 http body로 나눌 수도 있고, http body에 들어가는 json 구조로 분리할 수도
            있습니다.
          </li>
        </ol>
      </li>
      <li>
        API 버전을 관리합니다.
        <ol>
          <li>환경은 항상 변하기 때문에 API의 signature가 변경될 수도 있습니다.</li>
          <li>특정 API를 변경할 때는 반드시 하위호환성을 보장해야 합니다.</li>
        </ol>
      </li>
      <li>
        서버와 클라이언트가 같은 방식을 사용해서 요청하도록 합니다.
        <ol>
          <li>
            브라우저는 form-data 형식의 submit으로 보내고 서버에서는 json 형태로 보내는 식의 분리보다는 json으로 보내든,
            둘 다 form-data 형식으로 보내든 하나로 통일합니다.
          </li>
          <li>다른 말로 표현하자면 URI가 플랫폼 중립적이어야 합니다.</li>
        </ol>
      </li>
    </ol>
    <h3 id=""><a href="#">어떠한 장점이 존재하는가?</a></h3>
    <ol>
      <li>
        <strong>Open API를 제공하기 쉽습니다.</strong>
         REST는 표준화된 인터페이스와 자체 설명적인 메시지를 사용하기 때문에, 다른 개발자들이 쉽게 이해하고 사용할 수 있습니다.
      </li>
      <li>
        <strong>멀티플랫폼 지원 및 연동이 용이합니다.</strong>
         REST는 HTTP를 기반으로 하기 때문에, 다양한 플랫폼과 언어에서 손쉽게 구현하고 통신할 수 있습니다.
      </li>
      <li>
        <strong>원하는 타입으로 데이터를 주고 받을 수 있습니다.</strong>
         REST는 헤더에 MIME 타입을 명시함으로써, JSON,XML,TEXT 등 다양한 형식의 데이터를 송수신할 수 있습니다.
      </li>
      <li>
        <strong>기존 웹 인프라(HTTP)를 그대로 사용할 수 있습니다.</strong>
         REST는 HTTP의 기능과 제약을 최대한 활용하기 때문에, 별도의 인프라를 구축할 필요가 없습니다.
      </li>
    </ol>
    <h3 id=""><a href="#">단점은 뭐가 있을까?</a></h3>
    <ol>
      <li>
        <strong>사용할 수 있는 메소드가 한정적입니다.</strong>
         REST는 HTTP method를 사용하여 행위를 표현하기 때문에, CRUD 외의 복잡한 로직을 구현하기 어려울 수 있습니다.
      </li>
      <li>
        <strong>분산환경에는 부적합합니다.</strong>
         REST는 상태를 저장하지 않기 때문에, 여러 서버에 걸쳐서 작업을 처리하기 어려울 수 있습니다.
      </li>
      <li>
        <strong>HTTP 통신 모델에 대해서만 지원합니다.</strong>
         REST는 HTTP 프로토콜에 의존하기 때문에, 다른 프로토콜을 사용하는 웹 서비스와 호환되지 않을 수 있습니다.
      </li>
    </ol>
    <hr />
    <p>
      <a
        href="https://github.com/JaeYeopHan/Interview_Question_for_Beginner/tree/master/Development_common_sense"
        rel="external">
        참고
      </a>
    </p>
  </article>
</Post>
