<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="about-me"><a href="#about-me">About Me 👨‍💻</a></h2>
    <p>
      안녕하세요 <span class="wave">👋</span>
      <br />
      저는 0년차 웹 개발자입니다!
    </p>
    <h2 id="tech-stack-i-and-39-m-familiar-with">
      <a href="#tech-stack-i-and-39-m-familiar-with">Tech Stack I&#39;m familiar with</a>
    </h2>
    <p><ImgZoom src="/about/img.png" alt="img.png"></ImgZoom></p>
    <h2 id="education"><a href="#education">Education 🎓</a></h2>
    <p>
      <strong>전북대학교</strong>
       - [2015 - 2021]
    </p>
    <p>전기전공을 했으며, 졸업을 하고 개발자가 되기 위해 공부를 하고 있습니다.</p>
    <h2 id="certifications"><a href="#certifications">Certifications 🏅</a></h2>
    <ul>
      <li>
        <code class="inline-code-block">전기기사</code>
         - 한국산업인력공단
      </li>
      <li>
        <code class="inline-code-block">전기공사기사</code>
         - 한국산업인력공단
      </li>
      <li>
        <code class="inline-code-block">SQLD</code>
         - 한국데이터산업진흥원
      </li>
      <li>
        <code class="inline-code-block">컴퓨터활용능력 1급</code>
         - 대한상공회의소
      </li>
      <li>
        <del>
          <code class="inline-code-block">정보처리기사</code>
           공부중..!
        </del>
      </li>
    </ul>
  </article>
</Post>
