<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="jwt"><a href="#jwt">JWT란?</a></h2>
    <ul>
      <li>
        일반적으로 사용자의 인증 및 권한을 증명하기 위해 사용되며
        <ul>
          <li>서버와 클라이언트 간에 정보를 안전하게 전송하기 위한 수단</li>
        </ul>
      </li>
    </ul>
    <h2 id=""><a href="#">구성요소</a></h2>
    <p>
      JWT는 <code class="inline-code-block">.</code>
      을 구분자로 3가지의 문자열로 구성되어 있습니다. (
      <code class="inline-code-block">header</code>
      .
      <code class="inline-code-block">payload</code>
      .
      <code class="inline-code-block">signature</code>
      )
    </p>
    <h3 id="header"><a href="#header">헤더(Header)</a></h3>
    <p>헤더는 typ, alg 두가지의 정보를 지니고 있습니다.</p>
    <ul>
      <li>
        <code class="inline-code-block">typ</code>
         : 토큰의 타입 (JWT이기에 “JWT” 라는 값이 들어갑니다.)
      </li>
      <li>
        <code class="inline-code-block">alg</code>
         : 해싱 알고리즘을 지정합니다. 기본적으로 HMAC,SHA256,RSA가 사용되며 토큰을 검증 할때사용되는 signature부분에서 사용됩니다.
      </li>
    </ul>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-java">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token punctuation">{</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token string">"typ"</span> <span class="token operator">:</span> <span class="token string">"JWT"</span><span class="token punctuation">,</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token string">"alg"</span> <span class="token operator">:</span> <span class="token string">"HS256"</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token punctuation">}</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h3 id="payload"><a href="#payload">정보(Payload)</a></h3>
    <p>
      Payload 부분에는 토큰을 담을 정보가 들어있습니다. 정보의 한 조각을 클레임(Claim)이라고 부르고, 이는 name/value 한
      쌍으로 이뤄져있습니다. 토큰에는 여러개의 클레임들을 넣을 수 있지만 너무 많아질 경우 토큰의 길이가 길어질 수
      있습니다.
    </p>
    <p>클레임의 종류는 크게 세분류로 나누어집니다.</p>
    <p><strong>등록된(registerd) 클레임</strong></p>
    <p>
      등록된 클레임들은 서비스에서 필요한 정보들이 아닌, 토큰에 대한 정보들을 담기위하여 이름이 이미 정해진
      클레임들입니다. 등록된 클레임의 사용은 모두 선택적(Optional)이며, 이에 포함됟ㄴ 클레임 이름들은 다음과 같습니다.
    </p>
    <ul>
      <li>
        <code class="inline-code-block">iss</code>
         : 토큰 발급자(issuer)
      </li>
      <li>
        <code class="inline-code-block">sub</code>
         : 토큰 제목(subject)
      </li>
      <li>
        <code class="inline-code-block">aud</code>
         : 토큰 대상자(audience)
      </li>
      <li>
        <code class="inline-code-block">exp</code>
         : 토큰의 만료시간(expiration), 시간은 NumericDate형식으로 되어있어야하며 언제나 현재 시간보다 이후로 설정되어 있어야
        합니다.
      </li>
      <li>
        <code class="inline-code-block">nbf</code>
         : Not before를 의미하며, 토큰의 활성 날짜와 비슷한 개념입니다. 여기에도 NumericDate형식으로 날짜를 지정하며, 이
        날짜가 지나기 전까지는 토큰이 처리되지 않습니다.
      </li>
      <li>
        <code class="inline-code-block">iat</code>
         : 토큰이 발급된 시간(issued at)
      </li>
      <li>
        <code class="inline-code-block">jti</code>
         : JWT의 고유 식별자로서, 주로 중복적인 처리를 방지하기 위하여 사용됩니다. 일회용 토큰에 유용
      </li>
    </ul>
    <p><strong>공개(Public) 클레임</strong></p>
    <p>
      공개 클레임들은 충돌이 방지된(collision-resistant)이름을 가지고 있어야 합니다. 충돌을 방지하기 위해서는, 클레임
      이름을 URI형식으로 짓습니다.
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-java">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token punctuation">{</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token string">"https://kingseungil.oopy.io/jwt_claims/is_admin"</span> <span class="token operator">:</span> <span class="token boolean">true</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token punctuation">}</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><strong>비공개(Private) 클레임</strong></p>
    <p>
      등록된 클레임도 아니고, 공개된 클레임들도 아닙니다. 양 측간에(보통 클라이언트 ↔ 서버) 합의하에 사용되는 클레임
      이름들입니다. 공개 클레임과는 달리 이름이 중복되어 충돌이 될 수 있으니 사용할때에 유의해야 합니다.
    </p>
    <h3 id="signature"><a href="#signature">서명(Signature)</a></h3>
    <p>
      서명은 헤더의 인코딩값과 정보의 인코딩값을 합친 후, 주어진 비밀키로 해쉬를 하여 생성합니다. 이렇게 만든 해쉬를 <code
        class="inline-code-block">
        base64
      </code>
       형태로 나타내게 됩니다.
    </p>
    <hr />
    <h2 id="less-than-code-class-inline-code-block-greater-than-jwt-less-than-code-greater-than">
      <a href="#less-than-code-class-inline-code-block-greater-than-jwt-less-than-code-greater-than">
        💡 <code class="inline-code-block">JWT 장점</code>
      </a>
    </h2>
    <ul>
      <li>
        서버의 부하를 줄이고 세션 관리의 복잡성을 해결할 수 있습니다.
        <ul>
          <li>
            Self-contained방식으로 사용자에 대한 정보를 토큰 자체에 포함하고 있어서 별도의 저장소가 필요하지 않습니다.
          </li>
        </ul>
      </li>
      <li>
        다양한 플랫폼과 기기에서 사용할 수 있습니다
        <ul>
          <li>URL-safe한 문자열로 구성되어 있어서 HTTP 헤더나 URL 파라미터로 쉽게 전송할 수 있습니다.</li>
        </ul>
      </li>
      <li>다양한 인증 시나리오에 적용할 수 있습니다.</li>
    </ul>
    <h2 id="less-than-code-class-inline-code-block-greater-than-jwt-less-than-code-greater-than">
      <a href="#less-than-code-class-inline-code-block-greater-than-jwt-less-than-code-greater-than">
        🚨 <code class="inline-code-block">JWT 단점</code>
      </a>
    </h2>
    <ul>
      <li>네트워크의 부하를 증가시킬 수 있습니다</li>
      <li>Payload에 사용자에 대한 정보를 담고 있기 때문에 토큰의 크기가 커질 수 있습니다.</li>
      <li>토큰의 만료 시간을 변경하거나 취소하는 것이 어렵습니다.</li>
      <li>
        토큰은 서버에서 관리되지 않기 때문에 한번 발급된 토큰은 만료 시간이 지나기 전까지 유효합니다. <ul>
          <li>따라서 토큰의 재발급이 필요한 경우에는 추가적인 로직이 필요합니다.</li>
        </ul>
      </li>
    </ul>
    <hr />
    <p><a href="https://gyoogle.dev/blog/web-knowledge/JWT.html" rel="external">참고</a></p>
  </article>
</Post>
